In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("PJM_Load_hourly.csv")
df.head()

              Datetime  PJM_Load_MW
0  1998-12-31 01:00:00      29309.0
1  1998-12-31 02:00:00      28236.0
2  1998-12-31 03:00:00      27692.0
3  1998-12-31 04:00:00      27596.0
4  1998-12-31 05:00:00      27888.0

In [3]:
date_time=pd.to_datetime(df["Datetime"])
date_time.head()

0   1998-12-31 01:00:00
1   1998-12-31 02:00:00
2   1998-12-31 03:00:00
3   1998-12-31 04:00:00
4   1998-12-31 05:00:00
Name: Datetime, dtype: datetime64[ns]

In [4]:
#hour column
df["hour"]=date_time.dt.hour
df.head()

              Datetime  PJM_Load_MW  hour
0  1998-12-31 01:00:00      29309.0     1
1  1998-12-31 02:00:00      28236.0     2
2  1998-12-31 03:00:00      27692.0     3
3  1998-12-31 04:00:00      27596.0     4
4  1998-12-31 05:00:00      27888.0     5

In [5]:
#day of week
df["day_of_week"]=date_time.dt.dayofweek
df.head()

              Datetime  PJM_Load_MW  hour  day_of_week
0  1998-12-31 01:00:00      29309.0     1            3
1  1998-12-31 02:00:00      28236.0     2            3
2  1998-12-31 03:00:00      27692.0     3            3
3  1998-12-31 04:00:00      27596.0     4            3
4  1998-12-31 05:00:00      27888.0     5            3

In [6]:
#month extraction
df["month"]=date_time.dt.month
df.head()

              Datetime  PJM_Load_MW  hour  day_of_week  month
0  1998-12-31 01:00:00      29309.0     1            3     12
1  1998-12-31 02:00:00      28236.0     2            3     12
2  1998-12-31 03:00:00      27692.0     3            3     12
3  1998-12-31 04:00:00      27596.0     4            3     12
4  1998-12-31 05:00:00      27888.0     5            3     12

In [7]:
#is weekend
df["is_weekend"]=df["day_of_week"].apply(lambda x: 1 if x>=5 else 0)
df.head()

              Datetime  PJM_Load_MW  hour  day_of_week  month  is_weekend
0  1998-12-31 01:00:00      29309.0     1            3     12           0
1  1998-12-31 02:00:00      28236.0     2            3     12           0
2  1998-12-31 03:00:00      27692.0     3            3     12           0
3  1998-12-31 04:00:00      27596.0     4            3     12           0
4  1998-12-31 05:00:00      27888.0     5            3     12           0

In [8]:
!pip install holidays

Requirement already satisfied: holidays in /home/pavan-prasanth/anaconda3/envs/DSP/lib/python3.12/site-packages (0.69)
Requirement already satisfied: python-dateutil in /home/pavan-prasanth/anaconda3/envs/DSP/lib/python3.12/site-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/pavan-prasanth/anaconda3/envs/DSP/lib/python3.12/site-packages (from python-dateutil->holidays) (1.16.0)

In [9]:
## holiday
import holidays

holidays=holidays.US()

In [10]:
df["is_holiday"]=date_time.dt.date.apply(lambda x:1 if x in holidays else 0)
df.head()

,Datetime,PJM_Load_MW,hour,day_of_week,month,is_weekend,is_holiday
0,1998-12-31 01:00:00,29309.0,1,3,12,0,0
1,1998-12-31 02:00:00,28236.0,2,3,12,0,0
2,1998-12-31 03:00:00,27692.0,3,3,12,0,0
3,1998-12-31 04:00:00,27596.0,4,3,12,0,0
4,1998-12-31 05:00:00,27888.0,5,3,12,0,0

In [11]:
df["hour_sin"]=np.sin(2*np.pi*df["hour"] / 24)
df["hour_cos"]=np.cos(2*np.pi*df["hour"] / 24)
df.head()

,Datetime,PJM_Load_MW,hour,day_of_week,month,is_weekend,is_holiday,hour_sin,hour_cos
0,1998-12-31 01:00:00,29309.0,1,3,12,0,0,0.258819,0.965926
1,1998-12-31 02:00:00,28236.0,2,3,12,0,0,0.500000,0.866025
2,1998-12-31 03:00:00,27692.0,3,3,12,0,0,0.707107,0.707107
3,1998-12-31 04:00:00,27596.0,4,3,12,0,0,0.866025,0.500000
4,1998-12-31 05:00:00,27888.0,5,3,12,0,0,0.965926,0.258819

In [12]:
df["month_sin"]=np.sin(2*np.pi*df["month"]/12)
df["month_cos"]=np.cos(2*np.pi*df["month"]/12)
df.head()

,Datetime,PJM_Load_MW,hour,day_of_week,month,is_weekend,is_holiday,hour_sin,hour_cos,month_sin,month_cos
0,1998-12-31 01:00:00,29309.0,1,3,12,0,0,0.258819,0.965926,-2.449294e-16,1.0
1,1998-12-31 02:00:00,28236.0,2,3,12,0,0,0.500000,0.866025,-2.449294e-16,1.0
2,1998-12-31 03:00:00,27692.0,3,3,12,0,0,0.707107,0.707107,-2.449294e-16,1.0
3,1998-12-31 04:00:00,27596.0,4,3,12,0,0,0.866025,0.500000,-2.449294e-16,1.0
4,1998-12-31 05:00:00,27888.0,5,3,12,0,0,0.965926,0.258819,-2.449294e-16,1.0

In [ ]:
df.drop(["hour","month","Datetime"],axis=1,inplace=True)

In [15]:
df.head()

,PJM_Load_MW,day_of_week,is_weekend,is_holiday,hour_sin,hour_cos,month_sin,month_cos
0,29309.0,3,0,0,0.258819,0.965926,-2.449294e-16,1.0
1,28236.0,3,0,0,0.500000,0.866025,-2.449294e-16,1.0
2,27692.0,3,0,0,0.707107,0.707107,-2.449294e-16,1.0
3,27596.0,3,0,0,0.866025,0.500000,-2.449294e-16,1.0
4,27888.0,3,0,0,0.965926,0.258819,-2.449294e-16,1.0

In [32]:
train_size=int(0.8*len(df))
train=df.iloc[:train_size].copy()
test=df.iloc[train_size:].copy()

In [33]:
#calculating lag features for train data 
train["lag24"]=train["PJM_Load_MW"].shift(24)
train["lag168"]=train["PJM_Load_MW"].shift(168)
#calculating rolling features for train data
train["rolling_mean_24"]=train["PJM_Load_MW"].rolling(window=24).mean()

In [34]:
#calculating lag features for test data
test["lag24"]=test["PJM_Load_MW"].shift(24)
test["lag168"]=test["PJM_Load_MW"].shift(168)
#calculating rolling features for test data
test["rolling_mean_24"]=test["PJM_Load_MW"].rolling(window=24).mean()

In [37]:
train.dropna(inplace=True)
train.head()

,PJM_Load_MW,day_of_week,is_weekend,is_holiday,hour_sin,hour_cos,month_sin,month_cos,lag24,lag168,rolling_mean_24
168,27959.0,3,0,0,0.258819,0.965926,-2.449294e-16,1.0,26854.0,29309.0,27290.333333
169,26474.0,3,0,0,0.500000,0.866025,-2.449294e-16,1.0,25480.0,28236.0,27331.750000
170,25892.0,3,0,0,0.707107,0.707107,-2.449294e-16,1.0,24639.0,27692.0,27383.958333
171,25675.0,3,0,0,0.866025,0.500000,-2.449294e-16,1.0,24303.0,27596.0,27441.125000
172,25921.0,3,0,0,0.965926,0.258819,-2.449294e-16,1.0,24495.0,27888.0,27500.541667

In [60]:
test.dropna(inplace=True)
test.head(50)

,PJM_Load_MW,day_of_week,is_weekend,is_holiday,hour_sin,hour_cos,month_sin,month_cos,lag24,lag168,rolling_mean_24
26484,32359.0,1,0,0,-8.660254e-01,5.000000e-01,-1.0,-1.836970e-16,31423.0,32559.0,29575.500000
26485,31724.0,1,0,0,-7.071068e-01,7.071068e-01,-1.0,-1.836970e-16,30870.0,31943.0,29611.083333
26486,29751.0,1,0,0,-5.000000e-01,8.660254e-01,-1.0,-1.836970e-16,29241.0,30100.0,29632.333333
26487,27134.0,1,0,0,-2.588190e-01,9.659258e-01,-1.0,-1.836970e-16,26567.0,27145.0,29655.958333
26488,24195.0,2,0,0,0.000000e+00,1.000000e+00,-1.0,-1.836970e-16,24201.0,24521.0,29655.708333
26489,24419.0,0,0,0,2.588190e-01,9.659258e-01,-1.0,-1.836970e-16,26026.0,21478.0,29588.750000
26490,23461.0,0,0,0,5.000000e-01,8.660254e-01,-1.0,-1.836970e-16,24842.0,20543.0,29531.208333
26491,22875.0,0,0,0,7.071068e-01,7.071068e-01,-1.0,-1.836970e-16,23934.0,20205.0,29487.083333
26492,22718.0,0,0,0,8.660254e-01,5.000000e-01,-1.0,-1.836970e-16,23527.0,20163.0,29453.375000
26493,23225.0,0,0,0,9.659258e-01,2.588190e-01,-1.0,-1.836970e-16,23631.0,20709.0,29436.458333
26494,25032.0,0,0,0,1.000000e+00,6.123234e-17,-1.0,-1.836970e-16,25258.0,22578.0,29427.041667
26495,29256.0,0,0,0,9.659258e-01,-2.588190e-01,-1.0,-1.836970e-16,29085.0,26532.0,29434.166667
26496,31870.0,0,0,0,8.660254e-01,-5.000000e-01,-1.0,-1.836970e-16,31370.0,29016.0,29455.000000
26497,33019.0,0,0,0,7.071068e-01,-7.071068e-01,-1.0,-1.836970e-16,32018.0,29812.0,29496.708333
26498,34405.0,0,0,0,5.000000e-01,-8.660254e-01,-1.0,-1.836970e-16,32587.0,30368.0,29572.458333
26499,35511.0,0,0,0,2.588190e-01,-9.659258e-01,-1.0,-1.836970e-16,33007.0,30753.0,29676.791667
26500,36100.0,0,0,0,1.224647e-16,-1.000000e+00,-1.0,-1.836970e-16,33279.0,30843.0,29794.333333
26501,36531.0,0,0,0,-2.588190e-01,-9.659258e-01,-1.0,-1.836970e-16,33152.0,30630.0,29935.125000
26502,37177.0,0,0,0,-5.000000e-01,-8.660254e-01,-1.0,-1.836970e-16,33534.0,30558.0,30086.916667
26503,37238.0,0,0,0,-7.071068e-01,-7.071068e-01,-1.0,-1.836970e-16,33317.0,30230.0,30250.291667
26504,37075.0,0,0,0,-8.660254e-01,-5.000000e-01,-1.0,-1.836970e-16,32513.0,30007.0,30440.375000
26505,36920.0,0,0,0,-9.659258e-01,-2.588190e-01,-1.0,-1.836970e-16,32295.0,29963.0,30633.083333
26506,36634.0,0,0,0,-1.000000e+00,-1.836970e-16,-1.0,-1.836970e-16,31941.0,29996.0,30828.625000
26507,36446.0,0,0,0,-9.659258e-01,2.588190e-01,-1.0,-1.836970e-16,31258.0,30180.0,31044.791667
26508,37175.0,0,0,0,-8.660254e-01,5.000000e-01,-1.0,-1.836970e-16,32359.0,31855.0,31245.458333
26509,36110.0,0,0,0,-7.071068e-01,7.071068e-01,-1.0,-1.836970e-16,31724.0,31334.0,31428.208333
26510,34011.0,0,0,0,-5.000000e-01,8.660254e-01,-1.0,-1.836970e-16,29751.0,29586.0,31605.708333
26511,30961.0,0,0,0,-2.588190e-01,9.659258e-01,-1.0,-1.836970e-16,27134.0,26926.0,31765.166667
26512,28139.0,1,0,0,0.000000e+00,1.000000e+00,-1.0,-1.836970e-16,24195.0,24364.0,31929.500000
26513,24274.0,6,1,0,2.588190e-01,9.659258e-01,-1.0,-1.836970e-16,24419.0,21091.0,31923.458333
26514,23158.0,6,1,0,5.000000e-01,8.660254e-01,-1.0,-1.836970e-16,23461.0,20137.0,31910.833333
26515,21982.0,6,1,0,7.071068e-01,7.071068e-01,-1.0,-1.836970e-16,22875.0,19497.0,31873.625000
26516,21472.0,6,1,0,8.660254e-01,5.000000e-01,-1.0,-1.836970e-16,22718.0,19238.0,31821.708333
26517,21160.0,6,1,0,9.659258e-01,2.588190e-01,-1.0,-1.836970e-16,23225.0,19188.0,31735.666667
26518,21314.0,6,1,0,1.000000e+00,6.123234e-17,-1.0,-1.836970e-16,25032.0,19491.0,31580.750000
26519,21743.0,6,1,0,9.659258e-01,-2.588190e-01,-1.0,-1.836970e-16,29256.0,20166.0,31267.708333
26520,22282.0,6,1,0,8.660254e-01,-5.000000e-01,-1.0,-1.836970e-16,31870.0,21036.0,30868.208333
26521,24316.0,6,1,0,7.071068e-01,-7.071068e-01,-1.0,-1.836970e-16,33019.0,22876.0,30505.583333
26522,26394.0,6,1,0,5.000000e-01,-8.660254e-01,-1.0,-1.836970e-16,34405.0,24337.0,30171.791667
26523,27881.0,6,1,0,2.588190e-01,-9.659258e-01,-1.0,-1.836970e-16,35511.0,24924.0,29853.875000
26524,29194.0,6,1,0,1.224647e-16,-1.000000e+00,-1.0,-1.836970e-16,36100.0,25150.0,29566.125000
26525,30159.0,6,1,0,-2.588190e-01,-9.659258e-01,-1.0,-1.836970e-16,36531.0,24913.0,29300.625000
26526,30820.0,6,1,0,-5.000000e-01,-8.660254e-01,-1.0,-1.836970e-16,37177.0,24755.0,29035.750000
26527,31141.0,6,1,0,-7.071068e-01,-7.071068e-01,-1.0,-1.836970e-16,37238.0,24884.0,28781.708333
26528,31339.0,6,1,0,-8.660254e-01,-5.000000e-01,-1.0,-1.836970e-16,37075.0,24936.0,28542.708333
26529,31578.0,6,1,0,-9.659258e-01,-2.588190e-01,-1.0,-1.836970e-16,36920.0,25316.0,28320.125000
26530,31609.0,6,1,0,-1.000000e+00,-1.836970e-16,-1.0,-1.836970e-16,36634.0,25934.0,28110.750000
26531,31337.0,6,1,0,-9.659258e-01,2.588190e-01,-1.0,-1.836970e-16,36446.0,26888.0,27897.875000
26532,32566.0,6,1,0,-8.660254e-01,5.000000e-01,-1.0,-1.836970e-16,37175.0,28295.0,27705.833333
26533,32553.0,6,1,0,-7.071068e-01,7.071068e-01,-1.0,-1.836970e-16,36110.0,28159.0,27557.625000

In [39]:
features=["day_of_week","is_weekend","is_holiday","hour_sin","hour_cos","month_sin",
         "month_cos","lag24","lag168","rolling_mean_24"]
X_train=train[features]
X_test=test[features]
y_train=train["PJM_Load_MW"]
y_test=test["PJM_Load_MW"]

In [40]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((26148, 10), (6412, 10), (26148,), (6412,))

In [41]:
#scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [46]:
from sklearn.svm import SVR
svr=SVR(kernel='rbf', C=100)

In [47]:
svr.fit(X_train,y_train)

SVR(C=100)

In [48]:
y_pred=svr.predict(X_test)

In [49]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print("Mean_Squared_Error: ",mean_squared_error(y_test,y_pred))
print("Mean Absolute Error: ",mean_absolute_error(y_test,y_pred))
print("r2_score: ",r2_score(y_test,y_pred))

Mean_Squared_Error:  3946919.373001716
Mean Absolute Error:  1337.2250465236355
r2_score:  0.8958566108995791

In [51]:
import joblib
joblib.dump(svr,"model.pkl")
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']